drop table if exists category CASCADE;
drop table if exists content CASCADE;
drop table if exists title CASCADE;
drop table if exists todo CASCADE;
create table category (
    category_id integer generated by default as identity,
    name varchar(255),
    primary key (category_id)
);
create table content (
    content_id integer generated by default as identity,
    content varchar(255),
    primary key (content_id)
);
create table title (
    title_id integer generated by default as identity,
    title varchar(255),
    primary key (title_id)
);
create table todo (
    id integer generated by default as identity,
    fk_category_id integer,
    fk_content_id integer,
    fk_title_id integer,
    primary key (id)
);
alter table category
add constraint UK_46ccwnsi9409t36lurvtyljak unique (name);
alter table todo
add constraint FKa5cus3yv4lm12f7wanuuhbv0d foreign key (fk_category_id) references category on delete cascade;
alter table todo
add constraint FKbfs03rt6uqlxj2ntapawbrpui foreign key (fk_content_id) references content on delete cascade;
alter table todo
add constraint FK997tthjh3yov2x15ci16o2nki foreign key (fk_title_id) references title on delete cascade;